import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Yusuf Tasci",
  description: "Generated by Yusuf Tasci",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center justify-center p-3 bg-[#283127]">
          <div className="w-[10%] flex items-center justify-around">
            <a href="https://www.linkedin.com/in/yusuf-tasci-44a710264/">
              <Image
                src="/images/LinkedIn (1).svg"
                alt="Logo"
                width={33}
                height={38}
              />
            </a>
            <a href="https://github.com/Yusuf013">
              <Image 
                src="/images/GitHub.svg" 
                alt="Logo" 
                width={33} 
                height={38} />
            </a>
            <a href="https://www.instagram.com/yusuffffffff._/">
              <Image
                src="/images/Instagram.svg"
                alt="Logo"
                width={33}
                height={38}
              />
            </a>
          </div>
          <div className="w-[75%]  flex items-center justify-center ">
            <ul className="flex justify-center w-[100%] text-2xl text-[#F47519]">
              <li className="hover:text-[#FFFDE4] transition-colors duration-300">
                <Link href="/">Home</Link>
              </li>
              <li className="hover:text-[#FFFDE4] transition-colors duration-300 mx-32">
                <Link href="/aboutme">About me</Link>
              </li>
              <li className="hover:text-[#FFFDE4] transition-colors duration-300">
                <Link href="/projects">Projects</Link>
              </li>
            </ul>
          </div>
          <div className="w-[10%] flex items-center justify-center">
            <Link href="/contact">
              <button className="rounded-full bg-[#F47519] text-[#283127] font-bold px-3 py-1 hover:bg-[#FFFDE4] transition-colors duration-300">
                Contact
              </button>
            </Link>
          </div>
        </nav>
        <div className="background">{children}</div>
      </body>
    </html>
  );
}
